### ISSUE TITLE
Exemplar data not available

### ISSUE THREAD

**Issue by kenichi-shimada** [statimagcoll/MultiplexedNormalization#1]
Hi @ColemanRHarris,

Thanks for sharing the scripts for multiplexed normalization. I'm trying to run the sample codes available in the Rmd file, but have been stuck at loading the exemplar datasets:
```R
## load data from https://github.com/statimagcoll/atlasAnalysis
sc = atlasAnalysis::loadQuantifiedPCA()
```

> Error in gzfile(file, "rb") : cannot open the connection
> In addition: Warning message:
> In gzfile(file, "rb") :
>   cannot open compressed file '/media/disk2/atlas_mxif/data/colon map batch 1-3 position corrected w immune labels.rds', probable reason 'No such file or directory'

I've installed `atlasAnalysis`, but the code above was not successful because it seems the path indicates a locally mounted HDD. Could you make the rds file is available?

Thanks in advance,
Kenichi

**Comment by ColemanRHarris** [comment]
Hi @kenichi-shimada,

Thank you for the comment! Unfortunately that data is our collaborators, and we cannot share it. 

However, I would recommend going forward to use the R package we have developed for this problem: [https://github.com/ColemanRHarris/mxnorm](https://github.com/ColemanRHarris/mxnorm). In terms of development, we took much of the code and analyses from these scripts and adapted them into a more user-friendly package. Broadly, it includes a simulated dataset, S3 objects, and analysis methods for comparing normalization.
